name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  token:
    description: A token to the repository to manage issues and pull erquests.
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
