name: 🧪

on: [issues, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
    - uses: actions/checkout@v2
    - name: Run Action
      uses: ./
